"""
Confidence threshold policy for the reconciliation gating system.

Thresholds are loaded from config/policy.yaml (confidence_policy section) at
module import time.  If policy.yaml is absent or unreadable, the module falls
back to the hardcoded defaults in config_loader._DEFAULT_CONFIDENCE_POLICY.

To change thresholds: edit config/policy.yaml - do NOT edit this file.

Layout of POLICY:
  match_source  - per-source rules; auto_approve=True bypasses all confidence checks
  fix_type      - per-correction-type minimum confidence; the stricter of
                  match_source and fix_type min_confidence applies

The "_default" key is used when a specific match_source or fix_type is not found.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure config_loader is importable regardless of working directory.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from config_loader import load_confidence_policy, load_policy, load_reject_match_policy

_policy = load_policy()
POLICY  = load_confidence_policy(_policy)
_rm     = load_reject_match_policy(_policy)

# REVIEW confidence bands (when confidence is present but below threshold).
LOW_CONFIDENCE_FLOOR: float = float(POLICY.get("low_confidence_floor", 0.80))

# REJECT_MATCH safety-net thresholds - sourced from policy.yaml reject_match section.
REJECT_MATCH_CONF_THRESHOLD:  float = float(_rm.get("dob_name_conf_threshold",   0.75))
REJECT_MATCH_SALARY_RATIO:    float = float(_rm.get("salary_ratio_threshold",    2.5))
SALARY_RATIO_EXTREME_LOW:     float = float(_rm.get("extreme_salary_ratio_low",  0.85))
SALARY_RATIO_EXTREME_HIGH:    float = float(_rm.get("extreme_salary_ratio_high", 1.15))

# Validation log - confirms which source is in effect.
_yaml_path = Path(__file__).resolve().parents[2] / "config" / "policy.yaml"
if _yaml_path.exists():
    _ft = POLICY.get("fix_type", {})
    print(
        "[confidence_policy] Using policy.yaml thresholds: "
        f"salary={_ft.get('salary', {}).get('min_confidence', 0.97):.2f}, "
        f"status={_ft.get('status', {}).get('min_confidence', 0.98):.2f}, "
        f"hire_date={_ft.get('hire_date', {}).get('min_confidence', 0.95):.2f}, "
        f"job_org={_ft.get('job_org', {}).get('min_confidence', 0.95):.2f} | "
        f"reject_match: dob_name<{REJECT_MATCH_CONF_THRESHOLD:.2f}, "
        f"salary_ratio>{REJECT_MATCH_SALARY_RATIO:.1f}, "
        f"extreme_ratio=[{SALARY_RATIO_EXTREME_LOW:.2f},{SALARY_RATIO_EXTREME_HIGH:.2f}]"
    )
else:
    print(
        "[confidence_policy] policy.yaml not found - using internal defaults.",
        file=sys.stderr,
    )


def is_auto_approve_source(match_source: str) -> bool:
    """Return True iff this match_source unconditionally auto-approves all fix_types."""
    key = str(match_source).strip().lower()
    cfg = POLICY["match_source"].get(key, {})
    return bool(cfg.get("auto_approve", False))


def get_min_confidence(match_source: str, fix_type: str) -> float:
    """
    Return the strictest minimum confidence required for this (match_source, fix_type) pair.

    The stricter of the match_source threshold and the fix_type threshold is used.
    If match_source is auto_approve, returns 0.0 (always passes).
    """
    ms_key = str(match_source).strip().lower()
    ft_key = str(fix_type).strip().lower()

    if is_auto_approve_source(ms_key):
        return 0.0

    src_cfg = POLICY["match_source"].get(ms_key, POLICY["match_source"]["_default"])
    ft_cfg  = POLICY["fix_type"].get(ft_key,  POLICY["fix_type"]["_default"])

    src_min = src_cfg.get("min_confidence", 0.95)
    ft_min  = ft_cfg.get("min_confidence",  0.95)

    return max(src_min, ft_min)


def policy_summary() -> list[str]:
    """Return a human-readable list of policy lines for console display."""
    lines = []
    lines.append("Match-source policy:")
    for src, cfg in POLICY["match_source"].items():
        if src == "_default":
            continue
        if cfg.get("auto_approve"):
            lines.append(f"  {src:<20s}  AUTO-APPROVE (no confidence required)")
        else:
            lines.append(f"  {src:<20s}  min_confidence >= {cfg.get('min_confidence', 0.95):.2f}")
    lines.append(f"  {'(default)':<20s}  min_confidence >= {POLICY['match_source']['_default']['min_confidence']:.2f}")
    lines.append("")
    lines.append("Fix-type thresholds:")
    for ft, cfg in POLICY["fix_type"].items():
        if ft == "_default":
            continue
        lines.append(f"  {ft:<20s}  min_confidence >= {cfg.get('min_confidence', 0.95):.2f}")
    lines.append(f"  {'(default)':<20s}  min_confidence >= {POLICY['fix_type']['_default']['min_confidence']:.2f}")
    lines.append(f"  low_confidence threshold: < {LOW_CONFIDENCE_FLOOR:.2f}")
    return lines
